config/routes.rb
Rails.application.routes.draw do
  # resources :customers
  resources :customers do
    member do
      patch :toggle_status
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  match "/404", to: "errors#not_found", via: :all
  match "*path", to: "errors#not_found", via: :all
  root "customers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    enum :status, { active: "active", inactive: "inactive" }, default: "active"

    validates :first_name, :last_name, :phone_number, :status, :date_of_birth, presence: true
    validates :first_name, :last_name, :phone_number, length: { maximum: 50 }
    validates :phone_number, format: { with: /\A\d+\z/, message: "only allows numbers" }
    validates :phone_number, :email, uniqueness: true
    validate :date_of_birth_cannot_be_in_the_future
    validates :email, presence: true, format: { 
        with: /\A[^@\s]+@[^@\s]+\z/, 
        message: "must be a valid email address" 
    }

    def full_name
        "#{first_name} #{last_name}"
    end

    def date_of_birth_cannot_be_in_the_future
        return if date_of_birth.blank?

        dob = date_of_birth.is_a?(String) ? Date.parse(date_of_birth) : date_of_birth.to_date
        Rails.logger.debug "DEBUG: validating date_of_birth parsed = #{dob} vs today #{Date.current}"

        if dob > Date.current
            errors.add(:date_of_birth, "can't be in the future")
        end
    end

    scope :active, -> { where(status: "active") }
    scope :inactive, -> { where(status: "inactive") }
    scope :recent, -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found
  rescue_from ActionController::RoutingError, with: :render_not_found

  def toggle_status
    @customer = Customer.find(params[:id])
    @customer.active? ? @customer.update(status: "inactive") : @customer.update(status: "active")
    respond_to do |format|
      format.html { redirect_to @customer, notice: "Status updated to #{@customer.status}." }
      format.json { head :no_content }
    end
  end

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
    @customer = Customer.find(params[:id])
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy!

    respond_to do |format|
      format.html { redirect_to customers_path, notice: "Customer was successfully deleted.", status: :see_other }
      format.json { head :no_content }
    end
  end

  def record_not_found
    flash[:alert] = "Customer not found."
    redirect_to customers_path
  end

  def render_not_found
    render template: "errors/not_found", status: :not_found
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone_number, :email, :status, :date_of_birth)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render template: "errors/not_found", status: :not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <div class="row mb-0">
    <div class="col-md-12">
      <small class="m-0 text-muted">Customer Name:</small>
      <h2 class=" text-capitalize"><%= customer.full_name %></h2>
    </div>

    <div class="col-md-12 mb-3">
      <small class="m-0 text-muted">Status:</small>
      <%= (customer.active? ? '<span class="badge bg-success">Active</span>' : '<span class="badge bg-danger">Inactive</span>').html_safe %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6">
      <small class="m-0 text-muted">Phone number:</small>
      <p class="p-0 m-0 text-capitalize fw-bold"><%= customer.phone_number %></p> 
    </div>
    <div class="col-md-6">
      <small class="m-0 text-muted">Email:</small>
      <p class="p-0 m-0 text-capitalize fw-bold"><%= customer.email %></p>
    </div>
  </div>

  <div class="row mb-0">
    <div class="col-md-6">
      <small class="m-0 text-muted">Date of birth:</small>
      <p class="p-0 m-0 text-capitalize fw-bold"><%= customer.date_of_birth.present? ? customer.date_of_birth.strftime("%B %d, %Y") : "N/A" %></p> 
    </div>
    <div class="col-md-6">
      <small class="m-0 text-muted">Date added:</small>
      <p class="p-0 m-0 text-capitalize fw-bold"><%= customer.created_at.present? ? customer.created_at.strftime("%B %d, %Y") : "N/A" %></p> 
    </div>
  </div>

  <hr>
</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h5>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class: "form-control form-control-sm"  %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class: "form-control form-control-sm" %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number, class: "form-control form-control-sm" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control form-control-sm" %>
  </div>

  <div class="mb-3">
    <%= form.label :date_of_birth, class: "form-label" %>
    <%= form.date_field :date_of_birth, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Save Customer", class: "btn btn-sm btn-primary" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<% content_for :title, "Editing customer" %>

<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<% content_for :title, "Customers" %>
  <div>
    <p style="color: green"><%= notice %></p>
    <div class="mb-3">
      <h6 class="my-2 text-center">CUSTOMERS</h6>
    </div>

    <div id="customers">
      <div>
        <table id="customersTable" class="table table-striped">
          <thead>
            <tr>
              <th>Full Name</th>
              <th>Phone Number</th>
              <th>Status</th>
              <th>Date of Birth</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td class="text-capitalize"><%= customer.full_name %></td>
                <td><%= customer.phone_number %></td>
                <td><%= (customer.active? ? '<span class="badge bg-success">Active</span>' : '<span class="badge bg-danger">Inactive</span>').html_safe %></td>
                <td><%= customer.date_of_birth.present? ? customer.date_of_birth.strftime("%B %d, %Y") : "N/A" %></td>
                <td>
                  <%= link_to "View", customer, class: "btn btn-sm btn-primary" %>
                  <%= link_to "Edit", edit_customer_path(customer), class: "btn btn-sm btn-secondary" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>      
      </div>

    </div>

    <!-- <%= link_to "New Customer", new_customer_path, class: "btn btn-sm btn-primary mt-3" %> -->
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#customersTable').DataTable();
  });
</script>

app/views/customers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto bg-light p-3 shadow-sm rounded-3">
      <div class="mb-3">
        <h6 class="my-2 text-center">NEW CUSTOMER</h6>
      </div>

      <%= render "form", customer: @customer %>

      <br>

      <div>
        <%= link_to "Back to customers", customers_path %>
      </div>
    </div>
  </div>
</div>
      

app/views/customers/show.html.erb
<div class="container">
  <div >
    <p style="color: green"><%= notice %></p>
    <div class="mb-3">
        <h6 class="my-2 text-center">CUSTOMER DETAILS</h6>
    </div>
    <%= render @customer %>
    <div class="d-flex justify-content-between align-items-center mt-3">
      <div>
        <%= link_to "Back to customers", customers_path, class: "btn btn-sm btn-secondary me-3" %>
      </div>

      <div class="d-flex justify-content-end align-items-center">
        <div class="me-3">
          <%= form_with url: toggle_status_customer_path(@customer), method: :patch, local: true do %>
            <div class="form-check form-switch" >
              <input
                class="form-check-input"
                type="checkbox"
                name="status_toggle"
                id="flexSwitchCheckChecked"
                <%= 'checked' if @customer.active? %>
                onchange="if(confirm('Are you sure you want to toggle this customer\'s status?')) { this.form.submit(); } else { this.checked = !this.checked; }"
              />
              <label class="form-check-label" for="flexSwitchCheckChecked">Status: 
              <%= (@customer.active? ? '<span class="badge bg-success">Active</span>' : '<span class="badge bg-danger">Inactive</span>').html_safe %>
              </label>
            </div>
          <% end %>
        </div>

        <%= link_to "Edit", edit_customer_path(@customer), class: "btn btn-sm btn-primary me-3" %> 

        <%= button_to "Delete", @customer, method: :delete, class: "btn btn-sm btn-danger", onclick: "return confirm('Are you sure you want to delete this customer?');" %>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Customer Management App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/dataTables.bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="row m-0">
    <div class="col-md-8 mx-auto bg-light  shadow-sm rounded-3">
      <nav class="navbar navbar-expand-lg navbar-light bg-light ">
        <div class="container-fluid ">
          <a class="navbar-brand" href="/customers">Customer Management</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/customers">Customers</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/customers/new">Add New Customer</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div>
        <div class="p-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>
<style>
  body, html {
    background-color: #eee; 
  }
</style>